// Market data for the /home-values/ pages.
//
// Numbers come from src/data/market-data.csv, generated by scripts/import-rdc.mjs
// from Realtor.com's published ZIP-level file. Refresh with `npm run import:market`
// after downloading a new copy, then deploy. No API key, no live calls.
//
// Each row aggregates every ZIP assigned to that city, so `zips` may hold one
// entry or twenty. The pages show that list, since a figure covering 22 Milwaukee
// ZIPs and one covering a single suburb ZIP deserve different levels of trust.
//
// If a city in cities.js has no row in the CSV, getMarketStats returns null and
// the page says the data is not available. It never fills the gap with a guess.

// Vite inlines the CSV contents as a string at build time.
import csvText from '../data/market-data.csv?raw';

function num(v) {
  if (v == null || v === '') return null;
  const n = Number(String(v).replace(/[^0-9.]/g, ''));
  return isNaN(n) ? null : n;
}

// num() strips the minus sign, which is fine for prices and counts but would
// silently turn a year-over-year DROP into a rise. Signed values use this.
function signed(v) {
  if (v == null || String(v).trim() === '') return null;
  const n = Number(String(v).trim());
  return isNaN(n) ? null : n;
}

function loadRows() {
  const lines = csvText.split(/\r?\n/).filter((l) => l.trim() && !l.trim().startsWith('#'));
  const header = lines.shift().split(',').map((h) => h.trim());
  const idx = (name) => header.indexOf(name);
  const map = {};
  for (const line of lines) {
    const cells = line.split(',');
    const slug = (cells[idx('slug')] || '').trim();
    if (!slug) continue;
    map[slug] = {
      medianPrice: num(cells[idx('medianPrice')]),
      pricePerSqft: num(cells[idx('pricePerSqft')]),
      daysOnMarket: num(cells[idx('daysOnMarket')]),
      activeListings: num(cells[idx('activeListings')]),
      priceYoY: signed(cells[idx('priceYoY')]),
      priceMoM: signed(cells[idx('priceMoM')]),
      zips: (cells[idx('zips')] || '').trim().split(/\s+/).filter(Boolean),
      updated: (cells[idx('updated')] || '').trim(),
    };
  }
  return map;
}

const ROWS = loadRows();

function parseMonth(s) {
  const m = /^(\d{4})-(\d{1,2})/.exec(s || '');
  if (!m) return new Date();
  return new Date(Number(m[1]), Number(m[2]) - 1, 1);
}

// There used to be an estimate() here that manufactured a full set of figures
// for any city missing from the CSV: it derived a price per square foot by
// dividing a hand-guessed price, and produced days-on-market and listing counts
// from arithmetic on the ZIP digits. Those numbers described nothing. They were
// labelled "estimated figures" on the page, but a made-up number with a
// disclaimer under it is still a made-up number, and it looked exactly as
// authoritative as the real ones beside it.
//
// A city with no data now returns null and the page says so plainly. If that
// ever fires, the fix is to import real data, not to invent a placeholder.

// "up 4.6%" / "down 0.3%". Returns null when the source has no year-over-year
// figure, so the page can leave the tile out rather than show a fake zero.
export function fmtYoY(v) {
  if (v == null || isNaN(v)) return null;
  const pct = v * 100;
  if (Math.abs(pct) < 0.05) return 'Flat';
  return (pct > 0 ? '+' : '') + pct.toFixed(1) + '%';
}

export function fmtPrice(n) {
  if (n == null || isNaN(n)) return 'N/A';
  return '$' + Math.round(n).toLocaleString('en-US');
}

export function fmtNum(n) {
  if (n == null || isNaN(n)) return 'N/A';
  return Math.round(n).toLocaleString('en-US');
}

// Returns null when we have no real figures for this city.
export function getMarketStats(city) {
  const row = ROWS[city.slug];
  if (!row || row.medianPrice == null) return null;
  return {
    medianPrice: row.medianPrice,
    pricePerSqft: row.pricePerSqft,
    daysOnMarket: row.daysOnMarket,
    activeListings: row.activeListings,
    priceYoY: row.priceYoY,
    priceMoM: row.priceMoM,
    zips: row.zips.length ? row.zips : [city.zip],
    updated: parseMonth(row.updated),
  };
}
